code/api/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from api.views.elastic import ElasticViewSet
from api.views.note import (
    NoteListView,
    NoteDetailView,
    NoteCreateView,
    NoteUpdateView,
    NoteDeleteView,
)
from api.views.auth import (
    CustomLoginView,
    CustomRegisterView,
)

app_name = 'api'

# auth
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='api:login'), name='logout'),
    path('register/', CustomRegisterView.as_view(), name='register'),
]

# note
urlpatterns += [
    path('note/', NoteListView.as_view(), name='notes'),
    path('note/<int:pk>/', NoteDetailView.as_view(), name='note'),
    path('note/create/', NoteCreateView.as_view(), name='note-create'),
    path('note/edit/<int:pk>/', NoteUpdateView.as_view(), name='note-edit'),
    path('note/delete/<int:pk>/', NoteDeleteView.as_view(), name='note-delete'),
]

# elastic
urlpatterns += [
    path('elastic/', ElasticViewSet.as_view({"get": "list"}), name='elastic'),
]

code/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls')),
]

code/api/models/note.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Note(models.Model):
    title = models.CharField(max_length=128)
    description = models.CharField(default='', max_length=255)
    body = models.TextField(default='')
    link = models.TextField(default='', null=True, blank=True)
    done = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True, blank=True)
    due_to = models.DateTimeField(null=True, blank=True)

    user = models.ForeignKey(
        User,
        related_name='notes',
        on_delete=models.CASCADE
    )

    objects = models.Manager()

    def __str__(self):
        return f"<Note [self.id]: {self.title}>"

    def get_absolute_utl(self):
        return reverse("note_detail", args=[str(self.id)])

code/api/views/elastic.py
from django_elasticsearch_dsl_drf.viewsets import DocumentViewSet
from django_elasticsearch_dsl_drf.filter_backends import (
    FilteringFilterBackend,
    CompoundSearchFilterBackend,
)

from api.documents import NoteDocument
from api.serializers import NoteDocumentSerializer


class ElasticViewSet(DocumentViewSet):
    """
    to rebuild index, call:
        python code/manage.py search_index --rebuild
    to search, call
        http://localhost:8000/elastic/
    to search with query, call (trouble is the one of Note titles)
        http://localhost:8000/elastic/?search=trouble
    """
    document = NoteDocument
    serializer_class = NoteDocumentSerializer
    filter_backends = [
        FilteringFilterBackend,
        CompoundSearchFilterBackend,
    ]
    search_fields = ("title", "description", "body")
    multi_match_search_fields = ("title", "description", "body")
    filter_fields = {
        "title": "title",
        "description": "description",
        "body": "body"
    }

code/api/views/note.py
from django.urls import reverse_lazy
from api.models import Note
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin


class NoteListView(LoginRequiredMixin, ListView):
    model = Note
    context_object_name = "notes"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["notes"] = context["notes"].filter(user=self.request.user)

        search_input = self.request.GET.get("search-area") or ""

        if search_input:
            context["notes"] = context["notes"].filter(
                title__icontains=search_input
            )

        context["search_input"] = search_input

        return context


class NoteDetailView(LoginRequiredMixin, DetailView):
    model = Note
    context_object_name = "note"


class NoteCreateView(LoginRequiredMixin, CreateView):
    model = Note
    fields = [
        "title",
        "description",
        "body",
        "link",
        "due_to",
    ]
    success_url = reverse_lazy("api:notes")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(NoteCreateView, self).form_valid(form)


class NoteUpdateView(LoginRequiredMixin, UpdateView):
    model = Note
    fields = [
        "title",
        "description",
        "body",
        "link",
        "due_to",
    ]
    success_url = reverse_lazy("api:notes")


class NoteDeleteView(LoginRequiredMixin, DeleteView):
    model = Note
    context_object_name = "note"
    success_url = reverse_lazy("api:notes")

code/api/templates/api/note_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <a href="{% url 'api:notes' %}">Go Back</a>

    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure to delete this Note: {{ note }}?</p>
        <input type="submit" value="Delete">
    </form>

{% endblock content %}

code/api/templates/api/note_detail.html
{% extends 'base/base.html' %}

{% block content %}

    <div class="header-bar">
        <div>
            <h1>Node: {{ note.title }}</h1>
        </div>
        {% if request.user.is_authenticated %}
            <a href="{% url 'api:logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'api:login' %}">Login</a>
        {% endif %}
    </div>

    <hr>

    <div class="note-details">
        <p>{{ note.description }}</p>

        <p>{{ note.body }}</p>

        <p>{{ note.created_at }}</p>
    </div>

{% endblock content %}

code/api/templates/api/note_form.html
{% extends 'base/base.html' %}

{% block content %}

    <div class="header-bar">
        <p>Note Create</p>
    </div>

    <a href="{% url 'api:notes' %}">Go Back</a>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>

{% endblock content %}

code/api/templates/api/note_list.html
{% extends 'base/base.html' %}

{% block content %}

    <div class="header-bar">
        <div>
            <h1>My notes</h1>
        </div>
        {% if request.user.is_authenticated %}
            <a href="{% url 'api:logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'api:login' %}">Login</a>
        {% endif %}
    </div>

    <a href="{% url 'api:note-create' %}">Create a New one</a>

    <div class="note-search-wrapper">
        <form action="" method="get">
            {% csrf_token %}
            <input type="text" name="search-area">
            <input class="button" type="submit" value="Search">
        </form>
    </div>

    <div class="note-items-wrapper">
        {% for note in notes %}
        <div class="note-wrapper" data-position=""{{ note.pk }}>
            <div class="note-created-at">
                {{ note.created_at }}
            </div>
            <div class="note-title">
                <div class="note-icon"></div>
                <a class="edit-link" href="{% url 'api:note' note.id %}">{{ note.title }}</a>
            </div>
            <div class="note-controls">
                <a class="edit-link" href="{% url 'api:note-edit' note.id %}">Update</a>
                <a class="delete-link" href="{% url 'api:note-delete' note.id %}">Delete</a>
            </div>
        </div>
        {% endfor %}
    </div>



{% endblock content %}

code/api/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
    <title>Title</title>
    <style>
        body {
            background-color: #fff;
            font-family: 'Naunito', sans-serif;
            padding-top: 50px;
        }
        h1, h2, h3, h4, h5, h6 {
            font-family: 'Raleway', sans-serif;
        }
        a, p {
            color: #4b5156;
        }
        a {
            font-weight: 600;
        }
        input {
            outline: none;
            border: none;
        }
        .container {
            max-width: 800px;
            margin: auto;
            background-color: #fff;
            -webkit-box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
            box-shadow: 2px 2px 13px -4px rgbs(0, 0, 0, 0.21);
        }
        .header-bar {
            display: flex;
            justify-content: space-between;
            color: #fff;
            padding: 10px;
            border-radius: 5px 5px 0 0;
            background: linear-gradient(90deg, #eea390 0%, #eb796f 43%, #eb796f 100%);
        }
        .header-bar a {
            color: rgb(247, 247, 247);
            text-decoration: none;
        }
        .note-items-wrapper {
            display: flex;
            flex-direction: column;
            align-items: flex-start;
            justify-content: space-between;
            padding: 20px;
            border-radius: 5px 5px 0 0;
        }
        .note-wrapper {
            display: flex;
            align-items: center;
            justify-content: space-between;
            background-color: #fff;
            overflow: hidden;
        }
        .note-title {
            display: flex;
            padding: 20px;
        }
        .note-title a {
            text-decoration: none;
            color: #4b5156;
            margin-left: 10px;
        }
        .note-controls {

        }
        .delete-link {
            text-decoration: none;
            font-weight: 700;
            color: #cf4949;
            font-size: 22px;
            line-height: 0;
            padding: 20px 0;
        }
        .edit-link {
            text-decoration: none;
            font-weight: 900;
            color: cornflowerblue;
            font-size: 22px;
            line-height: 0;
            padding: 20px 0;
        }
        .button {
            border: 1px solid #757575;
            background-color: #fff;
            color: #eb796f;
            padding: 10px;
            font-size: 14px;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }
        @media screen and (max-width:320px) {
            #search-add-wrapper {
                padding: 10px;
            }
        }
        input[type=text],
        input[type=password],
        textarea {
            border: 1px solid #757575;
            border-radius: 5px;
            padding: 10px;
            width: 90%;
        }
        label {
            padding-top: 10px !important;
            display: block;
        }
    </style>
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>